### ISSUE TITLE
Kernel dies/segmentation fault when path is defined as a transposed array

### ISSUE THREAD

**Issue by lingyiyang** [datasig-ac-uk/esig#124]
With the default libalgebra backend, there is an issue when the path is defined as a transposed array (either using np.transpose or .T) causing a segmentation fault.

Minimum 'broken' example:
```python
import esig
import numpy as np

two_dim_stream1 = np.array([[0.11212,1.1212], [0.11, 0.22]])
print(esig.stream2sig(two_dim_stream1, 2))

two_dim_stream2 = np.transpose(np.array([[0.11212,0.11], [1.1212,0.22]]))
print(esig.stream2sig(two_dim_stream2, 2))
```

If we change the backend
```python
esig.set_backend("iisignature")
```
then computing signatures on transposed arrays works fine.

**Comment by terrylyons** [comment]
Historically the requirement used to be a contiguous numpy array. This might explain?  Sam might say more. Best

Terry

On 7 May 2022, at 00:28, lingyiyang ***@***.***> wrote:

﻿

With the default libalgebra backend, there is an issue when the path is defined as a transposed array (either using np.transpose or .T) causing a segmentation fault.

Minimum 'broken' example:

import esig
import numpy as np

two_dim_stream1 = np.array([[0.11212,1.1212], [0.11, 0.22]])
print(esig.stream2sig(two_dim_stream1, 2))

two_dim_stream2 = np.transpose(np.array([[0.11212,0.11], [1.1212,0.22]]))
print(esig.stream2sig(two_dim_stream2, 2))

If we change the backend

esig.set_backend("iisignature")

then computing signatures on transposed arrays works fine.

**Comment by lingyiyang** [comment]
I see, so the issue is likely that transpose returns a view, and computing signatures with libalgebra would still rely on the original allocation, which is then not contiguous.

**Comment by inakleinbottle** [comment]
Ok, so I thought I had properly accounted for this when I updated the code but this is an edge case that I did not consider. In the new code I use a Numpy function to create a copy of the array in contiguous form if it is not already contiguous. However, since transposition doesn't actually change the data, it simply changes the format from C-contiguous to F-contiguous (or vice versa), this function doesn't actually do anything. I actually need to handle the case where the array is F-contiguous.

I'll put together a hotfix on Monday.
